### ISSUE TITLE
Review of data_repair functions

### ISSUE THREAD

**Issue by tomoicki** [tomoicki/JobOffers_DataTransformation#1]
It's not urgent but if u find a second, please take a look at data_repair_functions.py and data_repair_procedure.py and let me know if u would change/improve anything.

**Comment by manelore** [comment]
https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/setup.py#L15
Usually it's not a good idea to pin to exact version in library requirements - you limit client if your lib to use those versions

JobOffers_DataTransformation - don't use camel case names of packages in Python. It may breake code analysis tools on different OSes and it doesn't look native in imports

https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L18
you can add element type also a typehint, aka
def xxx(p: list[dict[int, int]])
just prepend your file with `from __future__ import annotatins`
(this feature is available only in python 3.10, so we need
to enable it by importing from futures for older pythons)
in older python you can write
def xxx(p: typing.List[typing.Dict[int, int]])


https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L95
do you copy all function just to add this string?
just prepare your data before pass to this func
And in general copy-paste is one of the worst patterns

https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L54
do item.lower() once - no need to call .lower() again and again, it is slow
This function requires refactoring. 
at least something like this:
locations = { 
  'wars': 'Warszawa', 
  'lodz': 'Lodz',
  ...
}
or some 'for' loop over pairs ('wars', 'Warszawa') etc...

also replacement looks strage (checking for in)
we are replacing any string with 'ystok' with 'Bialostok'
even 'Korystok' or "xxxyyystok".. looks unstable



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L83
no need for `type(integ) == int`, it may be replaced with `try-catch-else`
try:
  int(item)
except ValueError:
  pass
else:
  loc_list.remove(item)


or better
if item.isalnum():
  loc_list.remove(item)


or even better add to the top of the function
loc_list = [x for x in loc_list if not x.isalnum()]



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L144
replaced if-elif-else with a "lookup table". add global variable with
currency_to_factor = {
  'USD': factor_usd,
  ...
}

and then just do `factor = currency_to_factor[given['currency']]


https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L144
don't iterate ovel all keys.
instead iterate over 3 keys and check if `key in given`



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L159
IMO a good candidate for 'lookup_table' {"hour": 8 * 30, "Year": 1 / 12, ...}
then you can remove 'if-ology'



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L212
functions looks very similar, they can be generalized into 1
reusable function `xxx(given, contract_types)`


https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L208
order of 'dict.keys()' is not defined
it is wrong to check something like "first item of d.keys()"
if you want to check that dict has only one key, do it explicitly
like `if dict.keys() == {'b2b'}:`



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L232
do we really need this function?
btw - bad name `pick_skills_from_DICTS`



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L239
just don't do that
it is slow (lookup table is much faster)
hard to maintain
hard to read
and just ugly

Also IMO checking for `in` is wrong here,
some other check (like `a.starswith(b)` or `a == b`) is better.



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L310
no need to add elements to list + convert to set 
just add elements directly to set


https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_functions.py#L315
does description of this function match to the actual code
something "Drops all skills which are not in `skills_x_plus` is better"
or even "Returns elements of list only prestened in another list"

btw. may be replaced with:
return [x for x in given if x in skills_x_plus]



https://github.com/tomoicki/JobOffers_DataTransformation/blob/34d87df0af58929d96d88dda3580b201b688e5ea/JobOffers_DataTransformation/data_repair_procedure.py#L10
maybe refactor to a for loop:

   for column_name, function_to_apply in [
     ('skills_must', data_repair_functions.nf_skills_repairer),
     ('skills_nice', data_repair_functions.nf_skills_repairer),
     ...
   ]:
     nofluff_data[column_name] = nofluff_data[column_name].map(function_to_apply)


overall it is very hard to read "monoblock" code
add empty lines, try to group similar things
try to find common patterns and someshow reuse code
don't be shy to add helper functions when they may improve readability

**Comment by tomoicki** [comment]
https://github.com/tomoicki/JobOffers_DataTransformation/pull/2

**Comment by tomoicki** [comment]
done
